### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Louis-7**
Correct locale parameter. Change "en-US" to "en_US" since "en-US" totally not working.

### CODE REVIEW

**Comment by ohtangza** [comment]
@Louis-7 Can you clarify your device condition? According to Apple's docs regarding locales (https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html), it seems that `en-US` seems to be right. It's also ISO standard string.

I'm also in use of this library and had no chance to encounter malfunctioning with this string.

**Comment by Louis-7** [comment]
Hi, sorry for late response. I'm using android. 

I was raise an issue here https://github.com/wenkesj/react-native-voice/issues/86

@jamsch, Could you answer the question from ohtangza?

**Comment by jamsch** [comment]
I looked at the link you sent @ohtangza Specifically this portion says to use the format:
`[language designator]_[region designator]` which follows the `en_US` pattern. 

selection_039

Here's a list of locale IDs for iOS
https://gist.github.com/xta/6e9b63db1fa662bb3910b680f9ebd458

For Android,  I don't think it matters so much but it seems like most examples use [Language tags](https://developer.android.com/reference/java/util/Locale.html#toLanguageTag()) which returns `[lang]-[region]` however [Locale.toString()] https://developer.android.com/reference/java/util/Locale#toString() returns  `[lang]_[region]` and [`LocaleList.getDefault()`](https://developer.android.com/guide/topics/resources/multilingual-support) returns the same format. 

[RecognizerIntent/EXTRA_LANGUAGE_PREFERENCE](https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_LANGUAGE_PREFERENCE) says to "use a locale string like 'en-US'." and doesn't elaborate beyond that.

**Comment by Louis-7** [comment]
I did some search and I find a post here -> [How to set the language in speech recognition on android?](https://stackoverflow.com/a/10548680/4436090) which excetly match the [source code](https://github.com/wenkesj/react-native-voice/blob/master/android/src/main/java/com/wenkesj/voice/VoiceModule.java#L107), it says "en-US" is the right parameter. 

But on my phone I'm sure about that `[language designator]-[region designator]` is not working for me, maybe I'm using a different language option from "en-US" but when you guys test the library you just use the English by default?

Maybe different version of OS have different format of language options. We may do more test on it.

**Comment by jamsch** [comment]
@Louis-7 
Yeah, I also read that. I'm not so sure it matters too much. One of the [follow up comments](https://stackoverflow.co/a/15447813) also suggest using 'en_US' instead, which is the same format as `java.utils.Locale.toString()`. Android hasn't documented this clearly.

**Comment by jamsch** [comment]
Just a note: iOS locales use the `[language designator]_[region designator]` syntax so it's probably best keeping 'en_US' as the default.

**Comment by Louis-7** [comment]
Anyway, we should find a way to notice other developers. Other people may have this issue either.

**Comment by sibelius** [comment]
better add this to another section of readme

**Pull request closed without merging**
