### PR TITLE
Enable file transcriptions

### PR DESCRIPTION
**Pull request by danieloi**
I've tested transcribing audio files for ios (as opposed to live-speech) with the changes on this PR and it worked 🎉

Before I clean up the JS & iOS API, tackle Android, etc, I wanted to see if any maintainer is keen on merging this contribution once I'm done working on it. 

If not, I'll spin off a new package for it. 

Also, my vscode editor autoformatted the code in the Voice.m file so the actual changes are fewer than what the diffs show. The main difference here is the setupAndTranscribe method I added. If there's a prettierrc for objective-c, I'd like to know 🤲🏽. 

URLs you pass for transcription should NOT include `file://` or you'll get a misleading permission error (that delayed this by a long time). 

Edits and suggestions/cleanups more than welcome!

### CODE REVIEW

**Comment by AlkanV** [comment]
TOP!!!!! i hope this will merged soon.

**Comment by AlkanV** [comment]
hello @danieloi, is there any mock up plan for android for how to handle transcription from file? because based on my research, the only work around solution for this, is record the audio in .flac format and send it to google transcription api, i could not find any other methods actually, it would be great if you also share your foundings.

an article from huawei: 
https://developer.huawei.com/consumer/en/doc/development/hiai-Guides/audio-file-transcription-0000001050040089
an example of how to implement such flow: 
https://github.com/katchsvartanian/voiceRecognition
more reading on stackoverflow 
https://stackoverflow.com/questions/2319735/voice-recognition-on-android-with-recorded-sound-clip
https://stackoverflow.com/questions/6989981/speech-to-text-from-own-sound-file

**Comment by danieloi** [comment]
@AlkanV I found [this thing about extra audio source](https://developer.android.com/reference/android/speech/RecognizerIntent#EXTRA_AUDIO_SOURCE) that looks relevant. 

Checking for that prefix is a nice idea. 

Haven't heard anything from the maintainers yet

**Comment by danieloi** [comment]
Decided to remove the draft status.

All that's left is figuring out the formatting that happened in the `Voice.m` file and updating the docs. 

Android's solution has a high chance of increasing bundle size by at least 40MB so it's better in a following PR

Ready for a look as is. 

Run the example app in the repo to test transcribing a pre-recorded file

**Comment by superandrew213** [comment]
@safaiyeh will you release a new version any time soon with this?

**Comment by bmbmjmdm** [comment]
> Decided to remove the draft status.
> 
> All that's left is figuring out the formatting that happened in the `Voice.m` file and updating the docs.
> 
> Android's solution has a high chance of increasing bundle size by at least 40MB so it's better in a following PR
> 
> Ready for a look as is.
> 
> Run the example app in the repo to test transcribing a pre-recorded file

@danieloi Could you make a draft PR with the android changes please? I'd like to try them out and see what I can do :)

**Pull request merged**
