### PR TITLE
fix(android): read minSdkVersion from root project

### PR DESCRIPTION
**Pull request by keremoge**

### CODE REVIEW

**Comment by safaiyeh** [comment]
Appreciate the PR @keremoge

**Comment by lecaro** [comment]
Hello! I'm having this issue with this new update... any suggestions, please please

>FAILURE: Build failed with an exception.
>
>* Where:
>Build file '...\node_modules\@react-native-voice\voice\android\build.gradle' line: 22
>
>* What went wrong:
>A problem occurred evaluating project ':react-native-voice_voice'.
> No signature of method: build_eqttlctslkgkjicqtt60194dp.android() is applicable for argument types: >(build_eqttlctslkgkjicqtt60194dp$_run_closure2) values: [build_eqttlctslkgkjicqtt60194dp$_run_closure2@5a5ac152]
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan >to get full insights.
>
>* Get more help at https://help.gradle.org
>
>BUILD FAILED in 9s
>

**Comment by safaiyeh** [comment]
@lecaro apologies, should have been released as a breaking change,  will revert and re-release

**Comment by lecaro** [comment]
Thank you @safaiyeh !!!

**Comment by keremoge** [comment]
I reopened a PR for a proper fix #320

**Pull request merged**
